---
include:
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/generic-ci.yml'
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/pipeline-jobs.yml'

variables:
  # These variables are set globally here:
  DOCKER_IMAGE_NAMESPACE: 'marcvs/build'
  DOCKER_IMAGE_NAME: 'pam-ssh-oidc-packaging'
  #TARGET_REPO: 'devel'
  # The following varialbes can be overwritten only in specific targets
  # REPO_BASE
  # REPO_USER
  # REPO_HOST

.deb-before-script: &deb-before-script
  - make get-sources

.rpm-before-script: &rpm-before-script
  - make get-sources
  - make patch-for-rpm
  - ls -la rpm


build-debian-buster:
  extends:
    - .build-debian-buster
    - .on-master
  before_script:
    - *deb-before-script
  # variables:
  #   REPO_BASE: '/var/www/prerel'

build-debian-bullseye:
  extends:
    - .build-debian-bullseye
    - .on-push-and-master
  before_script:
    - *deb-before-script

build-debian-bookworm:
  extends:
    - .build-debian-bookworm
    - .on-push-and-master
  before_script:
    - *deb-before-script



build-ubuntu-bionic:
  extends:
    - .build-ubuntu-bionic
    - .on-push-and-master
  before_script:
    - *deb-before-script

build-ubuntu-focal:
  extends:
    - .build-ubuntu-focal
    - .on-master
  before_script:
    - *deb-before-script

build-ubuntu-jammy:
  extends:
    - .build-ubuntu-jammy
    - .on-master
  before_script:
    - *deb-before-script

build-ubuntu-kinetic:
  extends:
    - .build-ubuntu-kinetic
    - .on-push-and-master
  before_script:
    - *deb-before-script

build-centos-7:
  extends:
    - .build-centos-7
    - .on-push-and-master
  before_script:
    - *rpm-before-script


build-centos-8:
  extends:
    - .build-centos-8
    - .on-master
  before_script:
    - *rpm-before-script

build-centos-stream:
  extends:
    - .build-centos-stream
    - .on-master
  before_script:
    - *rpm-before-script


build-rockylinux-8:
  extends:
    - .build-rockylinux-85
    - .never

build-rockylinux-8.5:
  extends:
    - .build-rockylinux-85
    - .on-master
  before_script:
    - *rpm-before-script


# Fedora container build fails with some GPG issues
#build-fedora-36:
#  extends:
#    - .build-fedora-36
#    - .on-push-and-master
#  before_script:
#    - *rpm-before-script


build-opensuse-leap-15.3:
  extends:
    - .build-opensuse-leap-153
    - .on-master
  before_script:
    - *rpm-before-script

build-opensuse-leap-15.4:
  extends:
    - .build-opensuse-leap-154
    - .on-master
  before_script:
    - *rpm-before-script

build-opensuse-leap-15.5:
  extends:
    - .build-opensuse-leap-155
    - .on-push-and-master
  before_script:
    - *rpm-before-script

build-opensuse-tumbleweed:
  extends:
    - .build-opensuse-tumbleweed
    - .on-master
  allow_failure: true
  before_script:
    - *rpm-before-script

integration-tests:
  stage: integration
  variables:
    PLUGIN_REF: main
    AGENT_REF: $CI_COMMIT_REF_NAME
  extends:
    - .on-push-and-master
  #rules:
  #  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  #  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    #  variables:
    #    TRIGGER_BRANCH: main
    #- if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    #  variables:
    #    TRIGGER_BRANCH: main
  inherit:
    variables: false
  trigger:
    project: m-team/integration/test-ssh-oidc
    branch: main
    strategy: depend
