---
include:
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/generic-ci.yml'
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/pipeline-jobs.yml'
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/distro-build-conditions.yml'


variables:
  # These variables are set globally here:
  DOCKER_IMAGE_NAMESPACE: 'marcvs/build'
  DOCKER_IMAGE_NAME: 'pam-ssh-oidc-packaging'
  PACKAGE_NAMES: 'pam-ssh-oidc pam-ssh-oidc-autoconfig'
  #TARGET_REPO: 'devel'
  # The following varialbes can be overwritten only in specific targets
  # REPO_BASE
  # REPO_USER
  # REPO_HOST

.deb-before-script: &deb-before-script
  - |
    make get-sources
    echo "### before-script ##############################################"
    echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"
    echo "CI_COMMIT_BRANCH:   ${CI_COMMIT_BRANCH}"
    echo "CI_DEFAULT_BRANCH:  ${CI_DEFAULT_BRANCH}"
    echo "CI_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}"
    echo "CI_UPSTREAM_PIPELINE_SOURCE:  ${CI_UPSTREAM_PIPELINE_SOURCE}"
    echo "CI_UPSTREAM_COMMIT_BRANCH:    $CI_UPSTREAM_COMMT_BRANCH"
    echo "CI_UPSTREAM_DEFAULT_BRANCH:   $CI_UPSTREAM_DEFAULT_BRANCH"
    echo "### /before-script ##############################################"

.rpm-before-script: &rpm-before-script
  - |
    set -x
    make get-sources
    make patch-for-rpm
    ls -la rpm
    set +x
    echo "### before-script ##############################################"
    echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"
    echo "CI_COMMIT_BRANCH:   ${CI_COMMIT_BRANCH}"
    echo "CI_DEFAULT_BRANCH:  ${CI_DEFAULT_BRANCH}"
    echo "CI_PIPELINE_SOURCE: ${CI_PIPELINE_SOURCE}"
    echo "CI_UPSTREAM_PIPELINE_SOURCE:  ${CI_UPSTREAM_PIPELINE_SOURCE}"
    echo "CI_UPSTREAM_COMMIT_BRANCH:    $CI_UPSTREAM_COMMT_BRANCH"
    echo "CI_UPSTREAM_DEFAULT_BRANCH:   $CI_UPSTREAM_DEFAULT_BRANCH"
    echo "### /before-script ##############################################"


build-debian-buster:
  extends:
    - .build-debian-buster
    - .build-conditions-debian-buster
  before_script:
    - *deb-before-script
  # variables:
  #   REPO_BASE: '/var/www/prerel'

build-debian-bullseye:
  extends:
    - .build-debian-bullseye
    - .build-conditions-debian-bullseye
  before_script:
    - *deb-before-script

build-debian-bookworm:
  extends:
    - .build-debian-bookworm
    - .build-conditions-debian-bookworm
  before_script:
    - *deb-before-script


build-ubuntu-bionic:
  extends:
    - .build-ubuntu-bionic
    - .build-conditions-ubuntu-bionic
  before_script:
    - *deb-before-script

build-ubuntu-focal:
  extends:
    - .build-ubuntu-focal
    - .build-conditions-ubuntu-focal
  before_script:
    - *deb-before-script

build-ubuntu-jammy:
  extends:
    - .build-ubuntu-jammy
    - .build-conditions-ubuntu-jammy
  before_script:
    - *deb-before-script

build-ubuntu-kinetic:
  extends:
    - .build-ubuntu-kinetic
    - .build-conditions-ubuntu-kinetic
  before_script:
    - *deb-before-script

build-centos-7:
  extends:
    - .build-centos-7
    - .build-conditions-centos-7
  before_script:
    - *rpm-before-script


build-centos-8:
  extends:
    - .build-centos-8
    - .build-conditions-centos-8
  before_script:
    - *rpm-before-script

build-centos-stream:
  extends:
    - .build-centos-stream
    - .build-conditions-centos-stream
  before_script:
    - *rpm-before-script


build-rockylinux-8:
  extends:
    - .build-rockylinux-85
    - .never

build-rockylinux-8.5:
  extends:
    - .build-rockylinux-85
    - .build-conditions-rockylinux-85
  before_script:
    - *rpm-before-script


# Fedora container build fails with some GPG issues
#build-fedora-36:
#  extends:
#    - .build-fedora-36
#    - .on-push-and-master
#  before_script:
#    - *rpm-before-script

build-opensuse-15.4:
  extends:
    - .build-opensuse-154
    - .build-conditions-opensuse-154
  before_script:
    - *rpm-before-script

build-opensuse-15.5:
  extends:
    - .build-opensuse-155
    - .build-conditions-opensuse-155
  before_script:
    - *rpm-before-script

build-opensuse-tumbleweed:
  extends:
    - .build-opensuse-tumbleweed
    - .build-conditions-opensuse-tumbleweed
  allow_failure: true
  before_script:
    - *rpm-before-script

integration-tests:
  stage: integration
  extends:
    - .on-push-and-master
  inherit:
    variables: false
  variables:
    # these variables are actually transported to the other side,
    # even though inherit:variables:false
    HORRIBLE_MESS: marcus-hates-this
    CI_UPSTREAM_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
    CI_UPSTREAM_COMMIT_BRANCH: $CI_COMMIT_BRANCH
    CI_UPSTREAM_DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
  trigger:
    project: m-team/integration/test-ssh-oidc
    branch: main
    strategy: depend

publish-all:
  extends:
    - .repo-definition
  stage: publish
  image: "marcvs/test_ssh-oidc_debian-bookworm:1"

  script:
    - !reference [.ssh-key-script]
    - |
      find results
      (cd results
          for DISTRO in *; do
              for R in ${DISTRO}/*; do
                  RELEASE=`basename $R`
                  echo "DISTRO:  ${DISTRO}"
                  echo "RELEASE: ${RELEASE}"
                  echo "user@host: ${REPO_USER}@${REPO_HOST}"
                  echo "PUBLISH_RESULTS_REPO: ${PUBLISH_RESULTS_REPO}"
                  [ -z "$PUBLISH_RESULTS_REPO" ] && {
                      echo "Error: PUBLISH_RESULTS_REPO is empty"
                      exit 2
                  }
                  # Ensure package version is not yet in pre-release
                  for FILE in ${DISTRO}/${RELEASE}/*rpm ${DISTRO}/${RELEASE}/*deb; do
                      [ -e ${FILE} ] || continue
                      echo "Handling file: $FILE"
                      MD5SUM=`md5sum $FILE | cut -d ' ' -f 1`
                      echo "MD5SUM: $MD5SUM - $FILE"
                      ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/is-file-in-repo.sh  -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE} -f `basename ${FILE}` -m ${MD5SUM}" || {
                          echo "Error: File does already exist OR there was an ssh error"
                          exit 1
                      }
                      echo "--------------------------------------------"
                  done
              done
          done
      )

      # None of the files is already in the repo, or only with an existing
      # md5sum.
      # Therefore, we can now copy files to new repo, and sign it
      echo "Uploading"
      (cd results
          for DISTRO in *; do
              for R in ${DISTRO}/*; do
                  RELEASE=`basename $R`
                  for FILE in ${DISTRO}/${RELEASE}/*rpm ${DISTRO}/${RELEASE}/*deb; do
                      [ -e ${FILE} ] || continue
                      # this is strange, but will make the file location
                      # be entirely be based on the remote ci-tools:
                      cat ${FILE} | ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/place-file-in-repo.sh -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE} -f `basename ${FILE}` -m ${MD5SUM}" || {
                          echo "Error placing ${FILE} "
                          exit 1
                      }
                      echo "--------------------------------------------"
                  done
                  ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/sign-repo.sh -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE}"
                  echo "============================================"
              done
          done
      )


      # Sign all involved prerel repos



